version: '3.9'
services:
  actionservice:
    build:
      context: .
      args:
        - version=0.1.0
    image: rasa-action-server:0.1.0
    container_name: action_server
    expose: [ 5055 ]
    volumes:
      - rasabot-content:/app/rasabot
  rasa:
    build:
      context: .
      dockerfile: DockerRasaS2H
    image: arturik/rasas2h:0.1.0
    container_name: rasa_server
    user: root
    ports:
      - "5005:5005"
      - "4000:4000"
    volumes:
      - rasabot-content:/app
volumes:
  rasabot-content:

