version: '3.9'
services:
  rasa:
    build:
      context: .
      dockerfile: DockerRasaS2H
    image: arturik/rasas2h:0.1.0
    container_name: rasa_server_dev
    user: root
    ports:
      - "5005:5005"
      - "4000:4000"
    volumes:
      - ./rasabot:/app
