version: '3.3'
services:
  rasa:
    image: rasa/rasa:2.2.2-full
    container_name: rasa_server_dev
    user: root
    ports:
      - 5006:5005
    volumes:
      - ../rasabot:/app
    command:
      [ "run", "--enable-api", "--log-file", "out.log" ]
